apiVersion: gateway.k8s.aws/v1
kind: LoadBalancerConfiguration
metadata:
  name: roboshop-alb
  namespace: roboshop
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
  - protocolPort: HTTPS:443
    certificates:
    - arn:aws:acm:us-east-1:970361933543:certificate/8bdec4bd-4a15-497e-8339-fc4c5e7bb5ca


# We are going to use ALB, Listener